# -*- coding: utf-8 -*-
"""PredictiveAnalyticsPrototype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GdX2NtpwKkCIUXNdPLu_d5Cj5nkXrpaT
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# pip install -q streamlit reportlab

import streamlit as st
import pandas as pd
import numpy as np
import io

# Optional ReportLab import with fallback
try:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

# ==========================================
# 1. PAGE CONFIGURATION & STYLING
# ==========================================
st.set_page_config(
    page_title="CII RT-153 Regularized QC Staffing Predictor",
    page_icon="🏗️",
    layout="wide"
)

# Custom CSS for Deep Navy Theme, Large Gray Crane Backdrop, and Dark Blue Button Text
st.markdown("""
<style>
    /* Global Font: Times New Roman */
    html, body, [class*="css"], .stApp, div, p, span, h1, h2, h3, h4, h5, h6,
    label, input, button, select, textarea, table, th, td, .stMarkdown {
        font-family: 'Times New Roman', Times, serif !important;
    }

    /* Main App Background: Deep Navy Blue */
    .stApp {
        background-color: #0F1E36 !important;
        color: #FFFFFF !important;
    }

    /* Headings & Text Colors */
    .main-header {
        font-size: 2.4rem;
        font-weight: 700;
        color: #FFFFFF !important;
        margin-bottom: 0.2rem;
    }
    .sub-header {
        font-size: 1.15rem;
        color: #CBD5E1 !important;
        margin-bottom: 1.5rem;
    }

    /* FIX: Streamlit Selectbox / Dropdown Popover Dark Styling */
    div[data-baseweb="select"] > div, input {
        background-color: #1E293B !important;
        color: #FFFFFF !important;
        border: 1px solid #3B82F6 !important;
    }

    /* Dropdown Options List Container */
    div[data-baseweb="popover"],
    div[data-baseweb="menu"],
    ul[role="listbox"],
    div[role="listbox"] {
        background-color: #1E293B !important;
        color: #FFFFFF !important;
        border: 1px solid #3B82F6 !important;
    }

    /* Dropdown Items */
    li[role="option"], div[role="option"] {
        background-color: #1E293B !important;
        color: #FFFFFF !important;
    }

    /* Dropdown Hover State */
    li[role="option"]:hover,
    li[role="option"][aria-selected="true"],
    div[role="option"]:hover {
        background-color: #2563EB !important;
        color: #FFFFFF !important;
    }

    /* BUTTON STYLING FIX: Dark Blue Text (#0F1E36) on High-Contrast Light Background */
    div.stButton > button {
        background-color: #60A5FA !important;
        color: #0F1E36 !important;
        font-weight: bold !important;
        font-size: 1.15rem !important;
        border: 2px solid #3B82F6 !important;
        border-radius: 8px !important;
        padding: 10px 20px !important;
    }
    div.stButton > button:hover {
        background-color: #93C5FD !important;
        color: #0F1E36 !important;
        border-color: #60A5FA !important;
    }

    /* Download Button Styling: Bold Dark Blue Text (#0F1E36) */
    div.stDownloadButton > button {
        background-color: #34D399 !important;
        color: #0F1E36 !important;
        font-weight: bold !important;
        font-size: 1.15rem !important;
        border: 2px solid #059669 !important;
        border-radius: 8px !important;
        padding: 10px 20px !important;
    }
    div.stDownloadButton > button:hover {
        background-color: #6EE7B7 !important;
        color: #0F1E36 !important;
    }

    /* Labels & Widget Text Contrast Override */
    label, p, span, div, h3, h4 {
        color: #FFFFFF !important;
    }

    /* Dataframe Table styling */
    .stDataFrame {
        background-color: #FFFFFF !important;
        border-radius: 6px;
        padding: 5px;
    }

    /* Metrics Card Overrides */
    div[data-testid="stMetricValue"] {
        color: #60A5FA !important;
    }

    /* LARGE FULL-APP BACKDROP GRAY CONSTRUCTION CRANE SVG */
    .crane-backdrop {
        position: fixed;
        bottom: -20px;
        right: -30px;
        width: 650px;
        height: 820px;
        z-index: 0;
        pointer-events: none;
        opacity: 0.25;
    }
</style>

<!-- High-Contrast Gray Backdrop Crane SVG Overlay -->
<div class="crane-backdrop">
    <svg width="650" height="820" viewBox="0 0 650 820" fill="none" xmlns="http://www.w3.org/2000/svg">
        <!-- Main Tower Lattice Columns -->
        <rect x="180" y="200" width="36" height="620" fill="#94A3B8"/>
        <!-- Lattice Cross Bracing -->
        <line x1="180" y1="240" x2="216" y2="280" stroke="#0F1E36" stroke-width="4"/>
        <line x1="180" y1="320" x2="216" y2="360" stroke="#0F1E36" stroke-width="4"/>
        <line x1="180" y1="400" x2="216" y2="440" stroke="#0F1E36" stroke-width="4"/>
        <line x1="180" y1="480" x2="216" y2="520" stroke="#0F1E36" stroke-width="4"/>
        <line x1="180" y1="560" x2="216" y2="600" stroke="#0F1E36" stroke-width="4"/>
        <line x1="180" y1="640" x2="216" y2="680" stroke="#0F1E36" stroke-width="4"/>
        <line x1="180" y1="720" x2="216" y2="760" stroke="#0F1E36" stroke-width="4"/>

        <!-- Tower Apex Peak Structure -->
        <polygon points="180,200 198,40 216,200" fill="#CBD5E1"/>

        <!-- Main Horizontal Crane Jib Beam -->
        <rect x="20" y="200" width="600" height="24" fill="#E2E8F0"/>

        <!-- Concrete Counterweight Blocks -->
        <rect x="30" y="224" width="80" height="50" fill="#64748B"/>

        <!-- Tension Stay Cables -->
        <line x1="198" y1="40" x2="30" y2="200" stroke="#CBD5E1" stroke-width="4"/>
        <line x1="198" y1="40" x2="600" y2="200" stroke="#CBD5E1" stroke-width="4"/>

        <!-- Trolley Assembly -->
        <rect x="460" y="224" width="28" height="14" fill="#64748B"/>
        <!-- Hoist Cable -->
        <line x1="474" y1="238" x2="474" y2="480" stroke="#E2E8F0" stroke-width="3" stroke-dasharray="8 6"/>

        <!-- Hook Block & Heavy Lifting Hook -->
        <rect x="458" y="480" width="32" height="28" fill="#94A3B8"/>
        <path d="M 474 508 C 460 520, 460 545, 478 545 C 490 545, 490 530, 478 530" stroke="#CBD5E1" stroke-width="5" fill="none"/>
    </svg>
</div>
""", unsafe_allow_html=True)

# ==========================================
# 2. MODEL PARAMETERS & CONSTANTS
# ==========================================
FACILITY_MULTIPLIERS = {
    "Chemical Plant": 1.25,
    "Oil/Gas Production Facility": 1.25,
    "Petrochemical Facility": 1.25,
    "Power Plant": 1.00,
    "Paper Plant": 1.00,
    "Food Processing Plant": 1.00,
    "Manufacturing Facility": 1.00,
    "Steel/Aluminum Mill": 1.00,
    "Pharmaceutical Plant": 1.10,
    "Water/Wastewater Treatment": 0.85,
    "Transportation Facility": 0.80,
    "General Building": 0.75
}

ENGINEERING_COMPLETION_MULTIPLIERS = {
    "< 20% Complete": 1.50,
    "21% - 40% Complete": 1.35,
    "41% - 60% Complete": 1.20,
    "61% - 80% Complete": 1.00,
    "81% - 95% Complete": 0.85,
    "> 95% Complete": 0.80
}

RAW_CRAFT_WEIGHTS = {
    "Piping": 1.83,
    "Electrical & Instrumentation": 1.10,
    "Equipment Installation": 0.90,
    "Civil": 0.70,
    "Structural": 0.70,
    "Other Crafts": 0.60
}

INDUSTRY_BENCHMARK_CRAFTS = {
    "Piping": 35.0,
    "Electrical & Instrumentation": 21.0,
    "Civil": 17.0,
    "Equipment Installation": 15.0,
    "Structural": 10.0,
    "Other Crafts": 2.0
}

# L2 Ridge Shrinkage (lambda = 0.35)
LAMBDA_SHRINKAGE = 0.35
REGULARIZED_CRAFT_WEIGHTS = {
    craft: round((1 - LAMBDA_SHRINKAGE) * w + LAMBDA_SHRINKAGE * 1.0, 3)
    for craft, w in RAW_CRAFT_WEIGHTS.items()
}

# ==========================================
# 3. AUTO-ADJUSTING SLIDER CALLBACK LOGIC
# ==========================================
CRAFT_KEYS = ["piping", "elec", "civil", "struct", "eqpt", "other"]

def adjust_crafts(changed_key):
    """Callback function that proportionally adjusts all other sliders when one slider is moved,
    ensuring the sum across all craft disciplines always equals exactly 100%."""
    new_val = st.session_state[changed_key]
    other_keys = [k for k in CRAFT_KEYS if k != changed_key]
    current_other_sum = sum(st.session_state[k] for k in other_keys)
    target_other_sum = 100 - new_val

    if target_other_sum <= 0:
        st.session_state[changed_key] = 100
        for k in other_keys:
            st.session_state[k] = 0
    elif current_other_sum > 0:
        scale = target_other_sum / current_other_sum
        adjusted_vals = {k: int(round(st.session_state[k] * scale)) for k in other_keys}

        diff = target_other_sum - sum(adjusted_vals.values())
        if diff != 0:
            largest_other = max(other_keys, key=lambda k: st.session_state[k])
            adjusted_vals[largest_other] += diff

        for k, v in adjusted_vals.items():
            st.session_state[k] = max(0, v)
    else:
        bm_defaults = {"piping": 35, "elec": 20, "civil": 15, "struct": 10, "eqpt": 10, "other": 10}
        bm_other_sum = sum(bm_defaults[k] for k in other_keys)
        adjusted_vals = {k: int(round(target_other_sum * (bm_defaults[k] / bm_other_sum))) for k in other_keys}

        diff = target_other_sum - sum(adjusted_vals.values())
        if diff != 0:
            adjusted_vals[other_keys[0]] += diff

        for k, v in adjusted_vals.items():
            st.session_state[k] = max(0, v)

# Initialize Session State values (Default sum = 100%)
if "piping" not in st.session_state:
    st.session_state.piping = 35
if "elec" not in st.session_state:
    st.session_state.elec = 20
if "civil" not in st.session_state:
    st.session_state.civil = 15
if "struct" not in st.session_state:
    st.session_state.struct = 10
if "eqpt" not in st.session_state:
    st.session_state.eqpt = 10
if "other" not in st.session_state:
    st.session_state.other = 10
if "report_generated" not in st.session_state:
    st.session_state.report_generated = False

# ==========================================
# 4. REGULARIZED ANALYTICS ENGINE WITH NaN-AWARE PARTITIONING
# ==========================================
def calculate_regularized_analytics(cost_m, facility_type, eng_comp, raw_craft_shares):
    m_type = FACILITY_MULTIPLIERS.get(facility_type, 1.00)
    m_engr = ENGINEERING_COMPLETION_MULTIPLIERS.get(eng_comp, 1.00)

    # NaN-Aware Residual Partitioning
    total_reported = sum(raw_craft_shares.values())
    final_craft_shares = {}

    reported_crafts = {k: v for k, v in raw_craft_shares.items() if v > 0}
    unreported_crafts = [k for k, v in raw_craft_shares.items() if v == 0]

    if total_reported < 99.0 and len(unreported_crafts) > 0:
        unallocated_capacity = 100.0 - total_reported
        unreported_bm_sum = sum(INDUSTRY_BENCHMARK_CRAFTS[c] for c in unreported_crafts)

        for craft, value in raw_craft_shares.items():
            if value > 0:
                final_craft_shares[craft] = value
            else:
                bm_weight = INDUSTRY_BENCHMARK_CRAFTS[craft]
                final_craft_shares[craft] = unallocated_capacity * (bm_weight / unreported_bm_sum)
    else:
        denom = max(1.0, total_reported)
        final_craft_shares = {k: (v / denom) * 100.0 for k, v in raw_craft_shares.items()}

    # Sub-linear Cost Power Scaling
    effective_cost = 10.0 * np.power(max(0.1, cost_m) / 10.0, 0.72)
    pei = effective_cost * m_type * m_engr
    base_qc = max(1.0, round(pei / 10.0, 1))

    # L2 Ridge Regularized Allocation
    weighted_shares = {}
    total_weighted_share = 0.0
    for craft, pct in final_craft_shares.items():
        w = REGULARIZED_CRAFT_WEIGHTS.get(craft, 1.00)
        w_val = (pct / 100.0) * w
        weighted_shares[craft] = w_val
        total_weighted_share += w_val

    qc_breakdown = {}
    for craft, w_val in weighted_shares.items():
        if total_weighted_share > 0:
            qc_breakdown[craft] = round(base_qc * (w_val / total_weighted_share), 2)
        else:
            qc_breakdown[craft] = 0.0

    # Winsorized Rework Prediction
    piping_pct = final_craft_shares.get("Piping", 35.0)
    raw_rework_pred = 1.2 + (m_engr * m_type * 2.1) + ((piping_pct / 100.0) * 1.8)
    predicted_rework = float(np.clip(raw_rework_pred, 0.8, 15.5))
    risk_level = "Low Risk" if pei < 25 else ("Moderate Risk" if pei <= 60 else "High Risk")

    return {
        "pei": round(pei, 2),
        "effective_cost": round(effective_cost, 2),
        "base_qc": base_qc,
        "predicted_rework": round(predicted_rework, 2),
        "risk_level": risk_level,
        "qc_breakdown": qc_breakdown,
        "final_craft_shares": final_craft_shares,
        "is_partially_imputed": total_reported < 99.0
    }

# ==========================================
# 5. REPORT GENERATOR (WITH MATHEMATICAL DECISION MODEL)
# ==========================================
def generate_pdf_report(project_name, cost_m, facility_type, delivery_method, contract_type, eng_comp, raw_shares, results):
    if REPORTLAB_AVAILABLE:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        story = []

        styles = getSampleStyleSheet()
        title_style = ParagraphStyle('DocTitle', parent=styles['Heading1'], fontName='Times-Bold', fontSize=18, textColor=colors.HexColor("#0F1E36"), spaceAfter=10)
        h2_style = ParagraphStyle('Heading2', parent=styles['Heading2'], fontName='Times-Bold', fontSize=12, textColor=colors.HexColor("#1F2937"), spaceBefore=10, spaceAfter=6)
        body_style = ParagraphStyle('Body', parent=styles['Normal'], fontName='Times-Roman', fontSize=9, leading=12)

        story.append(Paragraph("CII RT-153 Regularized QC Staffing & Mathematical Decision Report", title_style))
        story.append(Paragraph(f"<b>Project Identification:</b> {project_name} | <i>Analytics Engine: NaN-Aware L2 Regularized Model</i>", body_style))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#0F1E36"), spaceAfter=10))

        # Executive Summary
        story.append(Paragraph("Executive Summary & Predictive Outputs", h2_style))
        summary_data = [
            ["Actual Estimated Cost", f"${cost_m:,.2f}M", "Effective Exposure Cost (C_eff)", f"${results['effective_cost']:,.2f}M"],
            ["Project Exposure Index (PEI)", f"{results['pei']}", "Predicted Field Rework %", f"{results['predicted_rework']}%"],
            ["Total Recommended QC Staff", f"{results['base_qc']} FTE", "Overall Risk Assessment", results['risk_level']]
        ]
        t_summary = Table(summary_data, colWidths=[130, 110, 160, 110])
        t_summary.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F3F4F6")),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#D1D5DB")),
            ('FONTNAME', (0,0), (-1,-1), 'Times-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 8.5),
            ('PADDING', (0,0), (-1,-1), 5),
        ]))
        story.append(t_summary)
        story.append(Spacer(1, 10))

        # Staffing Table
        story.append(Paragraph("Recommended Discipline Staffing Allocation", h2_style))
        staff_data = [["Craft Discipline", "Final Workhour Share (%)", "L2 Regularized Weight", "Recommended QC Staff (FTE)"]]
        for craft, fte in results['qc_breakdown'].items():
            share = results['final_craft_shares'].get(craft, 0.0)
            weight = REGULARIZED_CRAFT_WEIGHTS.get(craft, 1.00)
            staff_data.append([craft, f"{share:.1f}%", f"{weight:.3f}", f"{fte:.2f} Inspectors"])

        t_staff = Table(staff_data, colWidths=[160, 120, 110, 130])
        t_staff.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor("#0F1E36")),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,-1), 'Times-Roman'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#D1D5DB")),
            ('FONTSIZE', (0,0), (-1,-1), 8.5),
            ('ALIGN', (1,0), (-1,-1), 'CENTER'),
            ('PADDING', (0,0), (-1,-1), 5),
        ]))
        story.append(t_staff)
        story.append(Spacer(1, 12))

        # MATHEMATICAL EXPLANATIONS SECTION
        story.append(Paragraph("Analytical Engine & Mathematical Decision Model", h2_style))
        math_text = """
        <b>1. Sub-Linear Power-Law Scale Regularization (Cost Scaling):</b><br/>
        To prevent large project budgets ($100M+) from driving unrealistically linear staffing demands, raw estimated cost (C) is regularized using a sub-linear power function (alpha = 0.72):<br/>
        <i>C_eff = 10 * (C_actual / 10)^0.72</i><br/>
        This models field management economies of scale where senior inspection leadership covers wider scopes as budget scales.<br/><br/>

        <b>2. Project Exposure Index (PEI):</b><br/>
        Combines scaled cost exposure with engineering design readiness at construction start (M_engr) and facility sector complexity (M_type):<br/>
        <i>PEI = C_eff * M_type * M_engr</i><br/><br/>

        <b>3. NaN-Aware Residual Workhour Partitioning:</b><br/>
        When direct labor input sums to less than 100%, explicitly reported craft percentages are locked exactly as entered. The remaining capacity (Delta = 100% - Sum_Reported) is partitioned exclusively among unreported (NaN) disciplines in proportion to their relative CII RT-153 industry benchmark weights:<br/>
        <i>P_u = Delta * [ Benchmark_u / Sum(Benchmark_unreported) ]</i><br/><br/>

        <b>4. L2 Ridge Regularization on Discipline Risk Weights:</b><br/>
        Empirical craft risk weights (w_d) derived from RT-153 field rework hours are shrunk toward the mean weight (1.0) using an L2 penalty (lambda = 0.35) to prevent extreme staff concentration on single-craft projects:<br/>
        <i>w_d_reg = (1 - lambda) * w_d_raw + lambda * (1.0)</i><br/><br/>

        <b>5. Winsorized Rework Prediction:</b><br/>
        Predicted field rework percentage is clamped within the 90th percentile empirical bounds [0.8%, 15.5%] to protect predictions from catastrophic one-off project outliers in the historical dataset.
        """
        story.append(Paragraph(math_text, body_style))

        doc.build(story)
        buffer.seek(0)
        return buffer, "application/pdf", f"Regularized_QC_Report_{project_name.replace(' ', '_')}.pdf"
    else:
        html_content = f"""
        <html>
        <head><title>QC Staffing Report - {project_name}</title></head>
        <body style="font-family: 'Times New Roman', serif; padding: 25px; color: #1F2937;">
            <h1 style="color: #0F1E36;">CII RT-153 Quality Control Staffing Report</h1>
            <h3>Project: {project_name}</h3>
            <hr style="border: 1px solid #0F1E36;">
            <h2>Executive Summary</h2>
            <ul>
                <li><b>Actual Estimated Cost:</b> ${cost_m:,.2f} Million</li>
                <li><b>Effective Exposure Cost (C_eff):</b> ${results['effective_cost']:,.2f} Million</li>
                <li><b>Project Exposure Index (PEI):</b> {results['pei']}</li>
                <li><b>Predicted Field Rework (Winsorized):</b> {results['predicted_rework']}%</li>
                <li><b>Total Recommended QC Staff:</b> {results['base_qc']} Inspectors</li>
            </ul>
            <h2>Discipline Breakdown</h2>
            <table border="1" cellpadding="8" cellspacing="0" style="border-collapse: collapse; width: 100%;">
                <tr style="background-color: #0F1E36; color: white;">
                    <th>Craft Discipline</th><th>Workhour Share (%)</th><th>Regularized Weight</th><th>QC Staff (FTE)</th>
                </tr>
                {"".join([f"<tr><td>{craft}</td><td>{results['final_craft_shares'][craft]:.1f}%</td><td>{REGULARIZED_CRAFT_WEIGHTS[craft]:.3f}</td><td>{fte:.2f} Inspectors</td></tr>" for craft, fte in results['qc_breakdown'].items()])}
            </table>
            <h2>Mathematical Decision Model</h2>
            <p><b>1. Sub-Linear Power Scaling:</b> C_eff = 10 * (Cost / 10)^0.72</p>
            <p><b>2. Project Exposure Index:</b> PEI = C_eff * M_type * M_engr</p>
            <p><b>3. NaN-Aware Partitioning:</b> Preserves reported crafts and assigns 100% - Sum_Reported strictly to unreported trades.</p>
            <p><b>4. L2 Ridge Shrinkage:</b> w_reg = 0.65 * w_raw + 0.35 * 1.0</p>
        </body>
        </html>
        """
        buffer = io.BytesIO(html_content.encode('utf-8'))
        return buffer, "text/html", f"Regularized_QC_Report_{project_name.replace(' ', '_')}.html"

# ==========================================
# 6. STREAMLIT USER INTERFACE
# ==========================================
st.markdown('<div class="main-header">CII RT-153 Regularized QC Staffing Analytics</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Predictive Field Rework Modeling & QC Inspector Staffing Allocation App</div>', unsafe_allow_html=True)

col_input, col_display = st.columns([1, 1.2], gap="large")

with col_input:
    st.subheader("📋 Project Configuration")
    project_name = st.text_input("Project Name / Identifier", value="Industrial Facility Project Alpha")

    col_c1, col_c2 = st.columns(2)
    with col_c1:
        cost_m = st.number_input("Estimated Cost ($ Millions)", min_value=0.1, max_value=2000.0, value=50.0, step=5.0)
        facility_type = st.selectbox("Facility Sector", list(FACILITY_MULTIPLIERS.keys()), index=0)
        delivery_method = st.selectbox("Project Delivery Method", ["EPC (Engineer-Procure-Construct)", "Design-Bid-Build", "Construction Management", "Other"], index=0)

    with col_c2:
        eng_comp = st.selectbox("Engineering Complete at Constr. Start", list(ENGINEERING_COMPLETION_MULTIPLIERS.keys()), index=2)
        contract_type = st.selectbox("Contract Type", ["Cost-Reimbursable / Cost Plus", "Cost Plus with Incentives", "Fixed Fee / Lump Sum", "Other"], index=0)

    st.markdown("---")
    st.subheader("👷 Craft Workhour Density (%)")
    st.caption("All sliders range from 0 to 100%. Adjusting any slider automatically scales the other trades so the total sum always equals 100%.")

    # SLIDERS WITH AUTOMATIC PROPORTIONAL REBALANCING CALLBACKS (Range: 0 - 100)
    piping = st.slider("Piping Craft %", min_value=0, max_value=100, key="piping", on_change=adjust_crafts, args=("piping",))
    elec = st.slider("Electrical & Instrumentation %", min_value=0, max_value=100, key="elec", on_change=adjust_crafts, args=("elec",))
    civil = st.slider("Civil Craft %", min_value=0, max_value=100, key="civil", on_change=adjust_crafts, args=("civil",))
    struct = st.slider("Structural Craft %", min_value=0, max_value=100, key="struct", on_change=adjust_crafts, args=("struct",))
    eqpt = st.slider("Equipment Installation %", min_value=0, max_value=100, key="eqpt", on_change=adjust_crafts, args=("eqpt",))
    other = st.slider("Other Crafts %", min_value=0, max_value=100, key="other", on_change=adjust_crafts, args=("other",))

    current_total = piping + elec + civil + struct + eqpt + other
    st.progress(min(1.0, max(0.0, current_total / 100.0)))
    st.success(f"✅ Total Allocated Craft Density: **{current_total}%**")

    raw_shares = {
        "Piping": piping,
        "Electrical & Instrumentation": elec,
        "Civil": civil,
        "Structural": struct,
        "Equipment Installation": eqpt,
        "Other Crafts": other
    }

results = calculate_regularized_analytics(cost_m, facility_type, eng_comp, raw_shares)

with col_display:
    st.subheader("📊 Robust Analytics & Staffing Plan")

    m1, m2, m3 = st.columns(3)
    with m1:
        st.metric("Predicted Field Rework", f"{results['predicted_rework']}%")
    with m2:
        st.metric("Total QC Inspectors", f"{results['base_qc']} FTE")
    with m3:
        st.metric("Project Exposure Index", f"{results['pei']}")

    st.caption(f"Effective Scale Cost: **${results['effective_cost']:,.1f}M** (regularized from raw ${cost_m:,.1f}M).")
    st.markdown("---")

    st.markdown("### Recommended Inspector Allocation by Discipline")

    df_staffing = pd.DataFrame([
        {
            "Craft Discipline": craft,
            "Input Density (%)": f"{raw_shares[craft]:.1f}%",
            "Final Used Density (%)": f"{results['final_craft_shares'][craft]:.1f}%",
            "L2 Weight": REGULARIZED_CRAFT_WEIGHTS[craft],
            "Inspectors (FTE)": fte
        }
        for craft, fte in results['qc_breakdown'].items()
    ])
    st.dataframe(df_staffing, use_container_width=True, hide_index=True)

    chart_data = pd.DataFrame({"Discipline": list(results['qc_breakdown'].keys()), "Inspectors (FTE)": list(results['qc_breakdown'].values())}).set_index("Discipline")
    st.bar_chart(chart_data)

    st.markdown("---")
    st.markdown("### 📄 Assessment Report Generation")

    # BUTTON TRIGGER FOR REPORT GENERATION (DARK BLUE TEXT #0F1E36)
    if st.button("⚡ Generate Inspection & QC Staffing Report", use_container_width=True):
        st.session_state.report_generated = True

    if st.session_state.report_generated:
        report_buffer, mime_type, file_name = generate_pdf_report(
            project_name=project_name, cost_m=cost_m, facility_type=facility_type,
            delivery_method=delivery_method, contract_type=contract_type,
            eng_comp=eng_comp, raw_shares=raw_shares, results=results
        )

        st.download_button(
            label=f"📥 Download Regularized Staffing Report ({'PDF' if REPORTLAB_AVAILABLE else 'HTML'})",
            data=report_buffer,
            file_name=file_name,
            mime=mime_type,
            use_container_width=True
        )